// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2CsiZFSsmaqXJxEq3Uo9RB9bScrZiQi8',
    appId: '1:116650883219:web:b3ab4b5821b59c5f1a3566',
    messagingSenderId: '116650883219',
    projectId: 'app1-6d82e',
    authDomain: 'app1-6d82e.firebaseapp.com',
    storageBucket: 'app1-6d82e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_yMiB9s6G7s9e7bzexU_JDx3i_Fjd4c4',
    appId: '1:116650883219:android:d60178dcdfd1c73d1a3566',
    messagingSenderId: '116650883219',
    projectId: 'app1-6d82e',
    storageBucket: 'app1-6d82e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpouhWL6kadAAWomsG2O6A-t8O6NzmQQU',
    appId: '1:116650883219:ios:10296eb7f1b07f491a3566',
    messagingSenderId: '116650883219',
    projectId: 'app1-6d82e',
    storageBucket: 'app1-6d82e.appspot.com',
    androidClientId: '116650883219-qpj40g5fbjtl99jvtg8e78kmt5479ltd.apps.googleusercontent.com',
    iosClientId: '116650883219-f3p6vpau5mdqkk3er8i5qtagk1gtiisr.apps.googleusercontent.com',
    iosBundleId: 'com.example.designapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpouhWL6kadAAWomsG2O6A-t8O6NzmQQU',
    appId: '1:116650883219:ios:10296eb7f1b07f491a3566',
    messagingSenderId: '116650883219',
    projectId: 'app1-6d82e',
    storageBucket: 'app1-6d82e.appspot.com',
    androidClientId: '116650883219-qpj40g5fbjtl99jvtg8e78kmt5479ltd.apps.googleusercontent.com',
    iosClientId: '116650883219-f3p6vpau5mdqkk3er8i5qtagk1gtiisr.apps.googleusercontent.com',
    iosBundleId: 'com.example.designapp',
  );
}
